### PR TITLE
Add fedora graphical base image

### PR DESCRIPTION
**Pull request by TristanCacqueray**

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
Unfortunately this is not enough because rpm fusion needs a fedora version number, preventing us from using `latest`.

**Comment by TristanCacqueray** [comment]
Ok, so we can use `$(rpm -E %fedora)` in the containerfile to get the version number of `latest`.

**Comment by juhp** [comment]
Well it is not bad, but the explicit gtk dep feels a bit suspicious.
eg why not gtk3 then instead? Perhaps it is some dependency(s) pulled in by gtk?
But also perfectly possible I am missing something here.

**Comment by JayDoubleu** [comment]
@TristanCacqueray any chance to add the ` x11 = True` to brave while you're at it ? 
I noticed on pure X11 sessions it's fine with wayland only but on Xwayland it requires it.

**Comment by TristanCacqueray** [comment]
@juhp @JayDoubleu it seems like gtk4 fixed the present issue observed in https://github.com/podenv/podenv/issues/91 . I think it's ok to aim for the latest version, and gtk4 is mostly a proxy to pull in the basic graphic stacks (e.g. cairo, pango, wayland-egl, ...).

Also regarding to the size concern, reading https://www.scrivano.org/posts/2021-10-26-compose-fs/ makes me think such solution may be not terribly inefficient, at least until ostree can be used natively. Thank you @juhp for the pointer :-)

**Comment by JayDoubleu** [comment]
To be brutally honest all guy apps from podenv so far installed all GUI deps from scratch so I personally will definitely appreciate single fatter image rather than multiple ;)

**Comment by TristanCacqueray** [comment]
Alright, thank you for the honest feedback, let me think about it some more. My concern is that this effectively enables fusion for things that should not need it. So perhaps there should be a `useGraphic` with the packages provided by fedora, for things like `zeal` or `audacity`, and `useGraphicCodec` to add libva and ffmpeg from fusion.

**Comment by JayDoubleu** [comment]
How's this going to work now, is it worth waiting for this to be rewritten/merged before adding more apps ?

**Comment by TristanCacqueray** [comment]
The Podenv.fedora module is going to provide new helper to simplify creating such fat image, basically we'll be able to replace `useSimple` and `useImage` with new helpers. I'll push something shortly.

**Comment by TristanCacqueray** [comment]
Alright, so eye balling the current dependencies of the hub applications, I extended the packages list with more common dependencies such as pipewire-libs and dejavu fonts. I guess we could automate that process of finding the most common requirements, but I think this PR is already a good improvement.

As you can see, most of the changes happen in the fedora module, please let me know if that works for you, then I'll merge it.

Also note that we can refactor the extra repository used by brave, vscode and wavebox with https://github.com/podenv/hub/pull/42 . This is similar to what I did for `addCopr` here.

**Comment by TristanCacqueray** [comment]
@juhp @JayDoubleu could you please let me know if the list of package in `extraGraphic` and `extraGraphicCodec` are relevant for you?

**Comment by JayDoubleu** [comment]
> @juhp @JayDoubleu could you please let me know if the list of package in `extraGraphic` and `extraGraphicCodec` are relevant for you?

Apologies, didn't have much time yet to spend on my SB build where I'm testing podenv. Will likely do so tomorrow

**Comment by TristanCacqueray** [comment]
Alright thanks, let's go with this initial PR.

**Comment by juhp** [comment]
Btw just noticed "dejavu-sans-mono-fonts" is listed twice.

**Pull request merged**
